[0m13:41:42.015178 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000265046BB470>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026503FCCCB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026503FCF230>]}
[0m13:41:42.018793 [debug] [MainThread]: An error was encountered while trying to send an event


============================== 13:41:42.019792 | 7b331247-d6cd-44cc-b586-fc698db1d9e8 ==============================
[0m13:41:42.019792 [info ] [MainThread]: Running with dbt=1.9.0
[0m13:41:42.019792 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\projects_github\\used_cars_dbt_project', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run --select dim_vehicle_colors', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:41:42.022300 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\projects_github\used_cars_dbt_project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:41:42.023298 [debug] [MainThread]: Command `dbt run` failed at 13:41:42.023298 after 0.21 seconds
[0m13:41:42.023298 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026504684800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002657E385AC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000265046BB470>]}
[0m13:41:42.023298 [debug] [MainThread]: An error was encountered while trying to send an event
[0m13:41:42.024298 [debug] [MainThread]: Flushing usage events
